"""Agregar columna productos_id a materiales

Revision ID: 5b34dc473127
Revises: 
Create Date: 2024-11-04 00:37:18.294277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b34dc473127'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productos_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'productos', ['productos_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('productos_id')

    # ### end Alembic commands ###
